server:
  port: 3000
database:
  name: rostering
  host: 172.104.98.121
  port: 5432
  user: aaron
  password: Joe25453229
  schema: public
  max_open_connections: 10
  max_idle_connections: 20
  partition_size: 10000
  partition_batch: 1000
